version: "3.9"

services:
  db:
    image: postgres:16
    container_name: student-habits-monitoring-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: student-habits-monitoring-adminer
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - "8080:8080"
    depends_on:
      - db

  grafana:
    image: grafana/grafana-oss
    container_name: student-habits-monitoring-grafana
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  postgres_data:
  grafana_data:
